#!/usr/bin/env python3
"""Regenerate edc16_trames.py from Renault's own DDT4ALL ECU definition.

Requires DDT4ALL installed (https://github.com/cedricp/ddt4all) so
EDC16_C3_VCD-X70(Diag_K).xml is available locally — it ships with the tool
rather than with this repo. Usage:

  uv run tools/gen_trames.py > edc16_trames.py
"""
import re
import sys
import xml.etree.ElementTree as ET

NS = "{http://www-diag.renault.com/2002/ECU}"
XML_PATH = r"C:\Program Files\DDT4ALL\ecus\EDC16_C3_VCD-X70(Diag_K).xml"

tree = ET.parse(XML_PATH)
root = tree.getroot()

# 1. Index every <Data Name="..."> by name -> scaling info
data_defs = {}
for data_el in root.iter(f"{NS}Data"):
    name = data_el.get("Name")
    bits_el = data_el.find(f"{NS}Bits")
    if bits_el is None:
        continue
    count = int(bits_el.get("count", "16"))
    signed = bits_el.get("signed", "0") == "1"
    scaled_el = bits_el.find(f"{NS}Scaled")
    if scaled_el is None:
        continue  # boolean/enum bit, not an analog value
    step_raw = scaled_el.get("Step")
    step = float(step_raw.strip()) if step_raw is not None else 1.0
    divide_by = scaled_el.get("DivideBy")
    divide_by = float(divide_by.strip()) if divide_by else 1.0
    offset = scaled_el.get("Offset")
    offset = float(offset.strip()) if offset else 0.0
    unit = scaled_el.get("Unit", "")
    data_defs[name] = {
        "bits": count,
        "signed": signed,
        "scale": step / divide_by,
        "offset": offset,
        "unit": unit,
    }

# 2. Walk Requests named "Trame A0".."Trame A8" and resolve each DataItem
target_trames = {f"A{i}": f"21A{i}" for i in range(9)}
results = {}
for req_el in root.iter(f"{NS}Request"):
    name = req_el.get("Name", "")
    m = re.match(r"^Trame (A\d)\b", name)
    if not m:
        continue
    trame_id = m.group(1)
    if trame_id not in target_trames:
        continue
    sent_el = req_el.find(f"{NS}Sent/{NS}SentBytes")
    received_el = req_el.find(f"{NS}Received")
    if sent_el is None or received_el is None:
        continue
    min_bytes = int(received_el.get("MinBytes", "0"))
    params = {}
    skipped_no_def = []
    skipped_bitflag = []
    for item_el in received_el.findall(f"{NS}DataItem"):
        item_name = item_el.get("Name")
        first_byte = item_el.get("FirstByte")
        bit_offset = item_el.get("BitOffset")
        if first_byte is None:
            continue
        if bit_offset is not None:
            skipped_bitflag.append(item_name)
            continue
        d = data_defs.get(item_name)
        if d is None:
            skipped_no_def.append(item_name)
            continue
        if item_name in params:
            continue  # some trames repeat a name at a different byte - keep first
        params[item_name] = {
            "first_byte": int(first_byte),
            "bits": d["bits"],
            "signed": d["signed"],
            "scale": d["scale"],
            "offset": d["offset"],
            "unit": d["unit"],
        }
    results[trame_id] = {
        "sent": sent_el.text.strip(),
        "min_bytes": min_bytes,
        "params": params,
        "skipped_no_def": skipped_no_def,
        "skipped_bitflag": skipped_bitflag,
    }

# 3. Emit the Python module
print("# Auto-generated by tools/gen_trames.py from Renault's own DDT4ALL ECU")
print("# definition (EDC16_C3_VCD-X70(Diag_K).xml — ships with the DDT4ALL diagnostic")
print("# tool). Do not hand-edit offsets/scales below; re-run the generator instead.")
print("#")
print("# Param names are kept in the original French (matching the exact signal names")
print("# a Renault/Dacia technician would recognize from their own tools), so this")
print("# data is directly usable when asking for help on a forum.")
print("#")
print('# Each trame\'s "params" maps a decoded signal name to:')
print("#   (first_byte, bit_width, signed, scale, offset, unit)")
print("# where first_byte is 1-indexed into the KWP2000 response (including the 2")
print("# leading SID/trame-id echo bytes), bit_width is 16 or 31 (a 31-bit field")
print("# occupies a full 4-byte big-endian word), and value = raw * scale + offset.")
print("TRAMES = {")
for trame_id in sorted(results, key=lambda k: int(k[1:])):
    r = results[trame_id]
    print(f'    "{trame_id}": {{')
    print(f'        "cmd": bytes.fromhex("{r["sent"]}"),')
    print(f'        "min_bytes": {r["min_bytes"]},')
    print('        "params": {')
    for pname, p in r["params"].items():
        safe_name = pname.replace('"', "'")
        print(f'            "{safe_name}": ({p["first_byte"]}, {p["bits"]}, {p["signed"]}, {p["scale"]!r}, {p["offset"]!r}, {p["unit"]!r}),')
    print("        },")
    print("    },")
print("}")

for trame_id in sorted(results, key=lambda k: int(k[1:])):
    r = results[trame_id]
    print(f"{trame_id}: {len(r['params'])} decodable, {len(r['skipped_bitflag'])} bit-flags skipped, {len(r['skipped_no_def'])} no-scaling-def skipped", file=sys.stderr)
    if r["skipped_no_def"]:
        print(f"  no-def: {r['skipped_no_def'][:10]}{'...' if len(r['skipped_no_def']) > 10 else ''}", file=sys.stderr)
